luck_num = [1,40,23,5,59]

begin
    num=1/0
rescue => exception
    puts exception
end